[package]
name = "oxide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = { version = "0.36.0", features = ["linked"] }
ash-window = "0.9.1"
env_logger = "0.9.0"
log = "0.4.14"
winit = "0.26.1"